# Generated by Django 4.1.2 on 2022-11-20 14:00

import chat_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_remove_chatmodel_is_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportermodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام نمایشی'),
        ),
        migrations.AlterField(
            model_name='supportermodel',
            name='score',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='supportermodel',
            name='supporter_uid',
            field=models.CharField(default=chat_app.utils.unique_username, editable=False, max_length=255, unique=True, verbose_name='آیدی پشتیبان'),
        ),
        migrations.AlterField(
            model_name='userchatmodel',
            name='user_chat_uid',
            field=models.CharField(default=chat_app.utils.unique_username, editable=False, max_length=255, unique=True, verbose_name='آیدی چت کاربر'),
        ),
    ]
