# Generated by Django 4.1.2 on 2022-11-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_supportermodel_full_name_alter_supportermodel_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportermodel',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='supportermodel',
            name='score',
        ),
    ]
