# Generated by Django 4.1.2 on 2022-12-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_rename_fullname_supportermodel_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('badterms', 'استفاده از کلمات نامناسب'), ('others', 'دلایل دیگر')], max_length=12, verbose_name='دلیل گزارش')),
                ('desc', models.TextField(verbose_name='متن گزارش')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.supportermodel', verbose_name='پشتیبان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.userchatmodel', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش کاربر',
                'verbose_name_plural': 'گزارش کاربران',
                'ordering': ['-id'],
            },
        ),
    ]
