# Generated by Django 4.1.2 on 2022-12-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_reportusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='آیا این پیام حذف شده است؟'),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='آیا این پیام ویرایش شده است؟'),
        ),
    ]
