# Generated by Django 4.1.2 on 2022-12-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_chatmodel_is_deleted_chatmodel_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='edited_num',
            field=models.IntegerField(default=0, verbose_name='تعداد اعمال ویرایش'),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='old_msg',
            field=models.TextField(blank=True, null=True, verbose_name='متن پیام قبل از ویرایش'),
        ),
    ]
