# Generated by Django 4.1.2 on 2022-12-03 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0008_chatmodel_edited_num_chatmodel_old_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='edited_num',
        ),
    ]
